apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-app
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=yashchauhan6660/ai-task-backend:~1.0,frontend=yashchauhan6660/ai-task-frontend:~1.0,worker=yashchauhan6660/ai-task-worker:~1.0

    argocd-image-updater.argoproj.io/write-back-method: argocd

    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/worker.update-strategy: semver

    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^v1\.0\.\d+$
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^v1\.0\.\d+$
    argocd-image-updater.argoproj.io/worker.allow-tags: regexp:^v1\.0\.\d+$

spec:
  project: default

  source:
    repoURL: https://github.com/yashchauhan66/ai-task-platform.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-plateform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true