apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ai-task-platform
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yashchauhan6660/ai-task-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI
        - name: Secret_Key
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: Secret_Key
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
