apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ai-task-plateform
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yashchauhan6660/ai-task-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 8
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 25
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_URI
        - name: Secret_Key
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: Secret_Key
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
