apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-task-health-ingress
  namespace: ai-task-plateform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
  - host: ai-task-plateform.duckdns.org
    http:
      paths:
      - path: /api/health
        pathType: Exact
        backend:
          service:
            name: backend-service
            port:
              number: 5000
