apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ai-task-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: ai-task-app
      useAnnotations: true
  writeBackConfig:
    method: argocd
