apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: ai-task-plateform
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: yashchauhan6660/ai-task-worker:v1.0.12
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_URI
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
